apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: default
  labels:
    name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      initContainers:
        - name: collectstatic
          image: asiwomex/django-todolist:v1.0
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: staticfiles
              mountPath: /static/
              readOnly: false
      containers:
        - name: django-todolist
          image: asiwomex/django-todolist:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: staticfiles
              mountPath: /static/
              readOnly: false
      volumes:
        - name: staticfiles
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  type: NodePort
  selector:
    name: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
