apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: tododb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tododb
  template:
    metadata:
      labels:
        app: tododb
    spec:
      containers:
        - name: mydb
          image: "{{ .Values.postgresImage.repository }}:{{ .Values.postgresImage.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresConfig.POSTGRES_DB }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresConfig.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresConfig.POSTGRES_PASSWORD }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-claim