apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secret
type: Opaque
stringData:
  DB_ENGINE: {{ .Values.env.DB_ENGINE }}
  DB_HOST: {{ .Values.env.DB_HOST }}
  DB_NAME: {{ .Values.env.DB_NAME }}
  DB_USER: {{ .Values.env.DB_USER }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD }}
  DB_PORT: "{{ .Values.env.DB_PORT }}"
